version: "3.2"
services:

  whoami:
    image: stefanscherer/whoami:insider
    networks:
      - demo
    environment:
      - PORT=8000
    volumes:
      - \\.\pipe\docker_engine:\\.\pipe\docker_engine
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.platform.os == windows

networks:
  demo:
    driver: overlay
